# Generated by Django 4.2.5 on 2023-09-30 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_profile_id_alter_profile_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='uuid',
            new_name='id',
        ),
    ]
