# Generated by Django 4.2.5 on 2023-10-01 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(blank=True, default='aman.jpeg', null=True, upload_to=''),
        ),
    ]
