# Generated by Django 4.2.5 on 2023-10-01 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_profile_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(blank=True, default='images/aman.jpeg', null=True, upload_to='images/'),
        ),
    ]
