# Generated by Django 4.2.5 on 2023-10-07 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_profile_following_profile_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='following',
        ),
    ]
