# Generated by Django 4.2.5 on 2023-09-28 09:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('post_image', models.ImageField(blank=True, default='aman.jpeg', null=True, upload_to='')),
                ('post_caption', models.TextField(blank=True, null=True)),
                ('post_created', models.DateTimeField(auto_now_add=True)),
                ('post_user', models.CharField(max_length=100)),
                ('post_likes', models.IntegerField(default=0)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
