# Generated by Django 4.2.5 on 2023-10-02 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_profile_profile_photo'),
        ('instaapp', '0002_alter_posts_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='post_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='likePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_like', to='users.profile')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_like', to='instaapp.posts')),
            ],
        ),
    ]
