# Generated by Django 4.2.5 on 2023-10-02 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instaapp', '0003_posts_post_name_likepost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likepost',
            old_name='username',
            new_name='post',
        ),
    ]
