# Generated by Django 4.2.5 on 2023-10-04 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instaapp', '0005_commentpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='post_name',
        ),
    ]
