# Generated by Django 4.2.5 on 2023-10-04 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaapp', '0006_remove_posts_post_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='post_videofile',
            field=models.FileField(null=True, upload_to='deploy/videos/%Y/%m/%d/', verbose_name=''),
        ),
    ]
