# Generated by Django 4.2.5 on 2023-10-04 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaapp', '0007_posts_post_videofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='post_videofile',
            new_name='post_video',
        ),
        migrations.AddField(
            model_name='posts',
            name='post_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
