# Generated by Django 4.2.5 on 2023-10-04 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaapp', '0009_alter_posts_post_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='post_video',
            field=models.FileField(null=True, upload_to='images/%Y'),
        ),
    ]
