# Generated by Django 4.2.5 on 2023-10-04 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instaapp', '0010_alter_posts_post_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='post_name',
        ),
    ]
