# Generated by Django 4.2.5 on 2023-10-04 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaapp', '0012_alter_posts_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='post_video',
            field=models.FileField(blank=True, null=True, upload_to='images/%Y'),
        ),
    ]
