# Generated by Django 4.2.5 on 2023-10-04 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaapp', '0013_alter_posts_post_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='post_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
