# Generated by Django 4.2.5 on 2023-10-04 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaapp', '0015_alter_posts_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='post_image',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
    ]
